### ISSUE TITLE
Add "details" property to boilerplate variables.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/boilerplate#11]
Consider the following

```yml
name: ElbHealthCheckType
    prompt: Enter the type for the health check (HTTP or TCP) the ELB will use to validate that a container is functioning. Use HTTP when your container returns an HTTP 200 response at var.elb_health_check_path. Use TCP when you merely want to validate that a connection can be made to the container. Valid values are HTTP, HTTPS, TCP, or SSL
```

That prompt is really long. I'd like to keep the `prompt` short and add a property like `details` that renders below the prompt and that's suitable for long-form text.

It'd also be nice to have something like an `enum` property that allows me to declare a set of valid values.

**Comment by brikis98** [comment]
Agreed, this would be very handy.

As for `enum`, see #9.

**Comment by brikis98** [comment]
In #14, I updated the way boilerplate prompts for variables to be similar to that of Terraform. I think it handles long descriptions much better now, so I'm going to close this. If you feel this needs more work, feel free to re-open.

**Comment by josh-padnick** [comment]
Thanks! Left some comments in #14. Either way, a definite improvement!
