### ISSUE TITLE
Cannot produce quoted JSON

### ISSUE THREAD

**Issue by yngvark** [gruntwork-io/boilerplate#168]
**Describe the bug**

The template

```json
{
  "foo": "{{ .Foo }}"
}
```

renders as an exact copy, without "Foo" being replaced by any input variable.

**To Reproduce**

```shell
cd $(mktemp -d)
mkdir -p bug/template
cd bug/template

cat <<EOF >boilerplate.yml
variables:
  - name: Foo
    type: string
EOF

cat <<EOF >example1.json
{
  "foo": "{{ .Foo }}"
}
EOF

cat <<EOF >example2.json
{
  "foo: "{{ .Foo }}"
}
EOF

boilerplate --template-url . --output-folder ../output --non-interactive --var Foo=Hello

cat ../output/example1.json
cat ../output/example2.json
```

**Expected behavior**

I expect the file `../output/example1.json` to contain

```json
{
  "foo": "Hello"
}
```

but it contains:

```text
{
  "foo": "{{ .Foo }}"
}
```

The template in `example1.json` works fine here: https://gotemplate.io.

**Nice to have**
- [ ] Terminal output
- [x] Screenshots

![image](https://github.com/gruntwork-io/boilerplate/assets/562343/a14d853d-8bda-42bc-8fcd-fefaf7ee5f09)

**Additional context**

boilerplate version v0.5.11

**Comment by brikis98** [comment]
Huh, very weird. I think there's something happening where the `{` and `}` at the beginning/ending of the file are causing issues. It seems like it _should_ work, so I'm not sure why that's the case, but while we investigate, the workaround is to "escape" those curly braces:

```
{{"{"}}
  "foo" : "{{ .Foo }}"
{{"}"}}
```

**Comment by brikis98** [comment]
I can also confirm that with totally standalone Go template, this rendering _should_ work:

```go
package main

import (
	"os"
	"text/template"
)

const json = `{
  "foo": "{{ .Foo }}"
}`

func main() {
	tmpl, err := template.New("test").Parse(json)
	if err != nil {
		panic(err)
	}
	err = tmpl.Execute(os.Stdout, map[string]string{"Foo": "bar"})
	if err != nil {
		panic(err)
	}
}
```

The output from running this is:

```
{
  "foo": "bar"
}
```

**Comment by brikis98** [comment]
@denis256 When you have a chance, could you take a look?

**Comment by denis256** [comment]
Will take a look soon

**Comment by denis256** [comment]
Fix included in https://github.com/gruntwork-io/boilerplate/releases/tag/v0.5.12
