### ISSUE TITLE
Input display issue

### ISSUE THREAD

**Issue by dnguyenzd** [gruntwork-io/boilerplate#170]
**Describe the bug**

I have a strange problem when running boilerplate. Below is a screen recording of the issue in a minimum template (example from the github repo). When I run boilerplate, it seems to insert a bunch of newlines before prompting for user input, make the display "jumpy". I don't think this is expected behavior? 

As can be seen from the screen capture, the last input (`ShowLogo`) with a default value is skipped and the default value is used automatically without any input from me. I expect to be prompted for the input, with the default value shown

https://github.com/gruntwork-io/boilerplate/assets/85463830/554b8edd-c849-459a-936e-b4022ae9750d

**To Reproduce**

the `boilerplate.yml` as in the screen capture
boilerplate v0.5.12
tried several options:
- zsh / bash
- with or without tmux
- alacritty or MacOS default terminal
- MacOS Ventura/Ubuntu

**Expected behavior**
- Input prompt without extra space on top
- Prompted for variables with default value

**Comment by Resonance1584** [comment]
Fixed in [v0.6.0](https://github.com/gruntwork-io/boilerplate/releases/tag/v0.6.0)
