### ISSUE TITLE
Question: obtain the relative path boilerplate working dir

### ISSUE THREAD

**Issue by xNok** [gruntwork-io/boilerplate#171]
Assuming that you run boilerplate at the root of a repo and want to start building a relative path to the root. How would you go about obtaining those paths?

Here is an example structure

```
. .boilerplate
| ` testfile.txt
+ subfolder
  ` + subsubfolder
     ` testfile.txt
```

Then then then I run

```
boilerplate --template-url ./.boilerplates/test --output-folder ./subfolder/subsubfolder
```

I would want `testfile.txt` to contain `./subfolder/subsubfolder`

I tried some hacks using shell, but interpolation does seem to occur in that way

```
{{ relPath outputFolder (shell echo "$PWD") }}
```

Maybe We could consider providing this out of the box in a variable.

```
{{ relPath outputFolder cmdPwd }}
```

**Comment by taylorsilva** [comment]
Just a I guess, but I have a feeling you might be able to do what you want with some of the sprig path functions: https://masterminds.github.io/sprig/paths.html

**Comment by brikis98** [comment]
Ah, adding a `workingDir` param to the context, which contains the path where you ran `boilerplate`, is a good idea. A PR for that is very welcome!

In the meantime, if you're looking for the root of a Git repo, perhaps with a shell command, you could use `git rev-parse --show-toplevel`?

**Comment by xNok** [comment]
I will look into making a PR, just need to put my head into the code at some point.

The best working solution so far

```
{{ relPath (env "PWD" "NO_FOUND") outputFolder }}
```
