### ISSUE TITLE
Saving answers and pre-filling questionnaire

### ISSUE THREAD

**Issue by kennyg** [gruntwork-io/boilerplate#173]
**Describe the solution you'd like**

I'd like a way to save answers to the  questions and a method to pre-fill the answers in the prompt. That would save users from having to fill in the text with answers. Useful for correcting wrong errors or iterating over the templates. 

**Describe alternatives you've considered**

**Additional context**

**Comment by brikis98** [comment]
Is this different than [`--var-file`](https://github.com/gruntwork-io/boilerplate?tab=readme-ov-file#variables)?

**Comment by kennyg** [comment]
Can you capture answers to questions and save them for future runs? I suppose if I could store previous answers in a wrapper script and generate this var file, that would solve this issue. On Mar 21, 2024, at 12:08 PM, Yevgeniy Brikman ***@***.***> wrote:﻿
Is this different than --var-file?
