### ISSUE TITLE
Use a file extension for templates that is removed from the rendered file

### ISSUE THREAD

**Issue by jon-ward-unmind** [gruntwork-io/boilerplate#177]
I'd like to be able to specify a file extension for my templates that will be removed from the rendered files in the output directory. For example, `main.tf.tmpl` would be rendered to `main.tf`. 

This would allow me to see at a glance whether a file is a template or not, and also avoid having to configure linting tools to ignore specific files or directories.

**Comment by brikis98** [comment]
Oh, interesting. More generally, I think a `rename` feature that supports file paths and patterns might be handy. A PR to add something along those lines is very welcome.

**Comment by staticaland** [comment]
This sounds similar to `gomplate` and its [`--output-map`](https://docs.gomplate.ca/usage/#--output-map).

**Comment by uthark** [comment]
One of the reason why it would be helpful is by using boilerplates for terragrunt scaffold. As of now, if you run `terragrunt destroy` it will scan full repo _including_ .boilerplate folder and will throw errors for the template 

```
17:37:31.157 ERROR  Expected an equals sign ("=") to mark the beginning of the attribute value.
17:37:31.157 WARN   Failed to parse HCL in file ../../../../../modules/smile/.boilerplate/terragrunt.hcl: ../../../../../modules/smile/.boilerplate/terragrunt.hcl:23,50-51: Unsupported operator; Bitwise operators are not supported. Did you mean boolean OR ("||")?, and 4 other diagnostic(s)
```

Related discussion is https://github.com/gruntwork-io/terragrunt/issues/4431 and https://github.com/gruntwork-io/terragrunt/issues/4060

**Comment by yhakbar** [comment]
Hey @uthark ,

We'll be adding support for hooks and shell commands in the Terragrunt integration with Boilerplate soon, which will allow you to get rid of the `.boilerplate` directory after generation using a hook:
https://github.com/gruntwork-io/boilerplate/releases/tag/v0.9.0

In the meantime, you can also use a `[before_hook](https://terragrunt.gruntwork.io/docs/features/hooks/)` to get rid of it before destroys.

As mentioned, a proposal for exactly how Boilerplate would handle this, and a PR to implement this would be welcome. This is not a priority for the maintainers right now.
