### ISSUE TITLE
Add support for variable types

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/boilerplate#9]
In line with #5, right now it's not possible to generate output terraform lists using boilerplate, just a string of comma-separated values. Adding support for lists would enable use of terraform 0.7's `list` type.

**Comment by brikis98** [comment]
I hope you don't object, but I'm going to rename this to "support types", as there are a number of types that would be useful:

* list
* map
* int
* bool
* enum

**Comment by josh-padnick** [comment]
Sounds good. I kept them separate to elucidate the separate use cases.

**Comment by brikis98** [comment]
Fixed with #20
